### ISSUE TITLE
Issue with Running Yelo Test on Kubernetes Cluster

### ISSUE THREAD

**Issue by atharva-kalbande** [atharva-aak/yolo-test#3]
**Title:** Issue Running Yelo Test on Kubernetes

**Description:**
I'm facing an issue while executing the Yelo test suite on a Kubernetes cluster. The test fails during runtime with unexpected behavior. The pod either crashes or the test job hangs indefinitely without completing.

**Environment:**
- Kubernetes Version: v1.27.3
- Yelo Version: [please specify]
- Cluster Type: [GKE / Minikube / Self-hosted]
- Node OS: Ubuntu 22.04
- Helm Version: 3.14.0 (if applicable)

**Steps to Reproduce:**
1. Apply the Yelo test manifest to the cluster:
   ```bash
   kubectl apply -f yelo-test.yaml
   ```
2. Monitor the pod/job status:
   ```bash
   kubectl get pods
   kubectl logs <yelo-pod-name>
   ```
3. Observe that the pod fails with the following error.

**Expected Behavior:**
The Yelo test should complete successfully, with logs indicating test pass/fail status and no crash or hang.

**Additional Context:**
- This issue started occurring after [e.g., cluster upgrade / manifest change].
- Here's a snippet of the deployment YAML:
  ```yaml
  apiVersion: batch/v1
  kind: Job
  metadata:
    name: yelo-test
  spec:
    template:
      spec:
        containers:
        - name: yelo
          image: yourregistry/yelo:latest
          command: ["./run-tests.sh"]
        restartPolicy: Never
  ```

Please let me know if more details are needed. Happy to provide full logs or YAML files.
